spring:
  jpa:
    properties:
      hibernate: 
        show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl       
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/authDB
    driver-class-name: com.mysql.jdbc.Driver
