spring:
    h2:
        console:
            enabled: true
            path: /console
    jpa:
        generate-ddl: false
        hibernate:
            naming: {physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl}
            ddl-auto: create
        show-sql: true
        database: h2
        database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        driver-class-name: org.h2.Driver
        data-password: null
        data-username: sa
        url: 'jdbc:h2:mem:testdb'
        platform: org.hibernate.dialect.H2Dialect
    security:
        oauth2:
            resource: null
            token-info-uri: 'http://localhost:8182/oauth/check_token'
            client: null
            client-id: web
            client-secret: webpass
